# Generated by Django 2.0.2 on 2021-05-15 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travellio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='desc',
        ),
    ]
